name: atgcn
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - openpyxl
  - pip:
    - tensorflow[and-cuda]
    - geopy
